# Generated by Django 5.2.7 on 2025-10-20 02:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={
                "ordering": ["-id"],
                "verbose_name": "계좌",
                "verbose_name_plural": "계좌들",
            },
        ),
    ]
